region: us-east-1

tags:
  - name: own
    value: what
  - name: foo
    value: bar

modules:
  compute:
    vars:
      - name: cidr
        type: list(string)
        description: test test
  network:
    vars:
      - name: ntest
        type: string
        description: test test

      - name: ntest2
        type: string
        description: test test



